<footer class="bg-slate-950 text-slate-300">
    <div class="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 md:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr] lg:px-8 lg:py-16">
        <div><a href="{{ route('home') }}" class="inline-flex items-center gap-2.5 rounded-md text-lg font-bold text-white focus-visible:ring-2 focus-visible:ring-brand-300"> <span class="grid h-9 w-9 place-items-center rounded-lg bg-brand-600 text-xs font-black">SR</span>Staff of <span class="-ml-2 text-brand-300">Rajasthan</span></a><p class="mt-4 max-w-sm text-sm leading-6 text-slate-400">A focused platform connecting people and employers across Rajasthan.</p></div>
        <div><h2 class="font-semibold text-white">Explore</h2><ul class="mt-4 space-y-3 text-sm"><li><a href="{{ route('jobs.index') }}" class="rounded-sm hover:text-white">Jobs</a></li><li><a href="{{ route('candidates.index') }}" class="rounded-sm hover:text-white">Candidates</a></li><li><a href="{{ route('companies.index') }}" class="rounded-sm hover:text-white">Companies</a></li><li><a href="{{ route('blog.index') }}" class="rounded-sm hover:text-white">Blog</a></li></ul></div>
        <div><h2 class="font-semibold text-white">About</h2><ul class="mt-4 space-y-3 text-sm"><li><a href="{{ route('about') }}" class="rounded-sm hover:text-white">Our platform</a></li><li><a href="{{ route('contact') }}" class="rounded-sm hover:text-white">Contact</a></li><li><a href="{{ route('login') }}" class="rounded-sm hover:text-white">Account login</a></li></ul></div>
        <div><h2 class="font-semibold text-white">For your next step</h2><p class="mt-4 text-sm leading-6 text-slate-400">Explore current roles or create an account to start your journey.</p><div class="mt-4 flex flex-wrap gap-2"><x-ui.button :href="route('register.candidate')" variant="soft" size="sm">Find a job</x-ui.button><x-ui.button :href="route('register.employer')" variant="secondary" size="sm">Hire talent</x-ui.button></div></div>
    </div>
    <div class="border-t border-slate-800"><div class="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-5 text-xs text-slate-400 sm:flex-row sm:justify-between sm:px-6 lg:px-8"><span>© {{ now()->year }} Staff of Rajasthan. All rights reserved.</span><span>Built for Rajasthan’s workforce.</span></div></div>
</footer>
