@extends('layouts.public')

@section('title', 'Find Jobs in Rajasthan | Staff of Rajasthan')

@section('content')
    <section class="bg-blue-50">
        <div class="mx-auto grid max-w-7xl items-center gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:py-24">
            <div>
                <p class="inline-flex rounded-full bg-white px-4 py-2 text-sm font-semibold text-blue-700 shadow-sm">Your next opportunity starts here</p>
                <h1 class="mt-6 max-w-2xl text-4xl font-extrabold tracking-tight text-slate-950 sm:text-6xl">Find a job that moves you forward</h1>
                <p class="mt-5 max-w-xl text-lg leading-8 text-slate-600">Discover meaningful work and growing teams across Rajasthan.</p>
                <form class="mt-8 grid gap-3 rounded-2xl bg-white p-3 shadow-lg shadow-blue-900/5 sm:grid-cols-[1fr_1fr_auto]" action="{{ route('jobs.index') }}" method="GET" role="search">
                    <label class="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3"><span class="text-blue-600" aria-hidden="true">⌕</span><span class="sr-only">Job title or keyword</span><input class="w-full border-0 p-0 text-sm focus:ring-0" name="keyword" placeholder="Job title or keyword"></label>
                    <label class="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3 sm:border-l"><span class="text-blue-600" aria-hidden="true">⌖</span><span class="sr-only">Location</span><input class="w-full border-0 p-0 text-sm focus:ring-0" name="location" placeholder="City or location"></label>
                    <button type="submit" class="rounded-xl bg-blue-700 px-6 py-3 text-sm font-bold text-white transition hover:bg-blue-800">Search jobs</button>
                </form>
                <div class="mt-5 flex flex-wrap items-center gap-2 text-sm"><span class="font-semibold text-slate-600">Popular searches:</span>@foreach ([['Jaipur', ['location' => 'Jaipur']], ['IT & Software', ['category' => 'it-software']], ['Sales', ['keyword' => 'Sales']], ['Remote', ['keyword' => 'remote']]] as [$label, $query])<a class="rounded-full border border-blue-200 bg-white px-3 py-1.5 text-blue-700 hover:border-blue-400" href="{{ route('jobs.index', $query) }}">{{ $label }}</a>@endforeach</div>
            </div>
            <div class="relative mx-auto w-full max-w-lg">
                <div class="absolute -inset-4 rounded-[2.5rem] bg-blue-100/80"></div>
                <div class="relative rounded-[2rem] border border-white bg-white p-7 shadow-xl sm:p-9">
                    <div class="flex items-center justify-between"><span class="font-bold text-slate-900">Rajasthan opportunities</span><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Live platform</span></div>
                    <div class="mt-7 grid grid-cols-2 gap-4"><div class="rounded-2xl bg-blue-50 p-5"><p class="text-3xl font-extrabold text-blue-700">{{ number_format($jobCount) }}</p><p class="mt-1 text-sm text-slate-600">Open jobs</p></div><div class="rounded-2xl bg-slate-50 p-5"><p class="text-3xl font-extrabold text-slate-900">{{ number_format($categoryCount) }}</p><p class="mt-1 text-sm text-slate-600">Career fields</p></div></div>
                    <div class="mt-6 space-y-3"><div class="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span class="grid h-10 w-10 place-items-center rounded-lg bg-amber-50 text-amber-700">✦</span><div><p class="text-sm font-semibold">Real employer listings</p><p class="text-xs text-slate-500">Published and current opportunities</p></div></div><div class="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span class="grid h-10 w-10 place-items-center rounded-lg bg-emerald-50 text-emerald-700">⌖</span><div><p class="text-sm font-semibold">Rooted in Rajasthan</p><p class="text-xs text-slate-500">Roles from local companies and teams</p></div></div></div>
                </div>
            </div>
        </div>
    </section>

    <section id="categories" class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wider text-blue-700">Find your field</p><h2 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Popular categories</h2><p class="mt-2 text-slate-600">Explore active career areas and their current openings.</p></div><a href="{{ route('jobs.index') }}" class="font-semibold text-blue-700 hover:text-blue-900">Browse all jobs <span aria-hidden="true">→</span></a></div>
        @if ($categories->isEmpty())<div class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">Categories will appear as the job board is configured.</div>@else<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach ($categories as $category)<x-category-card :category="$category" />@endforeach</div>@endif
    </section>

    <section id="jobs" class="bg-white"><div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wider text-blue-700">Handpicked opportunities</p><h2 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Featured jobs</h2></div><a href="{{ route('jobs.index') }}" class="font-semibold text-blue-700 hover:text-blue-900">See all jobs <span aria-hidden="true">→</span></a></div>
        @if ($featuredJobs->isEmpty())<div class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><p class="font-semibold text-slate-800">No featured jobs are published yet.</p><p class="mt-1 text-sm text-slate-500">Check the latest opportunities or return soon.</p></div>@else<div class="mt-8 grid gap-4 lg:grid-cols-3">@foreach ($featuredJobs as $job)<x-job-card :job="$job" />@endforeach</div>@endif
    </div></section>

    <section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wider text-blue-700">Recently published</p><h2 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Latest jobs</h2></div><a href="{{ route('jobs.index') }}" class="font-semibold text-blue-700 hover:text-blue-900">Browse the job directory <span aria-hidden="true">→</span></a></div>
        @if ($latestJobs->isEmpty())<div class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><p class="font-semibold text-slate-800">There are no current job listings.</p><p class="mt-1 text-sm text-slate-500">New employer listings will appear here when they are published.</p></div>@else<div class="mt-8 grid gap-4">@foreach ($latestJobs as $job)<x-job-card :job="$job" layout="list" />@endforeach</div>@endif
    </section>

    <section id="companies" class="bg-slate-100"><div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-wider text-blue-700">Meet the teams</p><h2 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Popular employers</h2></div><span class="text-sm text-slate-500">Companies with published opportunities</span></div>
        @if ($companies->isEmpty())<div class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">Employer profiles will appear here when companies publish jobs.</div>@else<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach ($companies as $company)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid h-12 w-12 place-items-center overflow-hidden rounded-xl bg-blue-50 font-bold text-blue-700">@if ($company->logo_path)<img class="h-full w-full object-cover" src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($company->logo_path) }}" alt="{{ $company->name }} logo">@else{{ mb_substr($company->name, 0, 1) }}@endif</div><h3 class="mt-4 font-bold text-slate-950">{{ $company->name }}</h3><p class="mt-1 text-sm text-slate-500">{{ $company->industry?->name ?? 'Employer' }}{{ $company->location?->name ? ' · '.$company->location->name : '' }}</p><p class="mt-4 text-sm font-semibold text-blue-700">{{ number_format($company->jobs_count) }} {{ \Illuminate\Support\Str::plural('open role', $company->jobs_count) }}</p></article>@endforeach</div>@endif
    </div></section>

    <section id="about" class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div class="grid gap-5 lg:grid-cols-2"><article class="rounded-3xl bg-blue-700 p-8 text-white sm:p-10"><p class="text-sm font-bold uppercase tracking-wider text-blue-100">For job seekers</p><h2 class="mt-3 text-3xl font-extrabold">Make your next move count.</h2><p class="mt-3 max-w-lg leading-7 text-blue-50">Build a candidate profile, add your resume and skills, and explore real opportunities across Rajasthan.</p><a href="{{ route('register.candidate') }}" class="mt-6 inline-flex rounded-lg bg-white px-5 py-3 font-bold text-blue-800 transition hover:bg-blue-50">Create candidate account</a></article><article class="rounded-3xl border border-slate-200 bg-white p-8 sm:p-10"><p class="text-sm font-bold uppercase tracking-wider text-blue-700">For employers</p><h2 class="mt-3 text-3xl font-extrabold text-slate-950">Meet the people who move your business forward.</h2><p class="mt-3 max-w-lg leading-7 text-slate-600">Create an employer account and prepare your company profile for the upcoming hiring tools.</p><a href="{{ route('register.employer') }}" class="mt-6 inline-flex rounded-lg bg-blue-700 px-5 py-3 font-bold text-white transition hover:bg-blue-800">Create employer account</a></article></div></section>
@endsection
