@extends('layouts.public')

@section('title', $candidate->user->name.' | Candidate Profile | Staff of Rajasthan')
@section('description', Str::limit(strip_tags($candidate->about ?: ($candidate->headline ?: 'Public professional profile on Staff of Rajasthan.')), 155))
@section('canonical', route('candidates.show', $candidate->slug))
@section('og_type', 'profile')

@section('content')
    <section class="bg-[#f3f7ff]"><div class="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><x-ui.breadcrumbs :items="[['label'=>'Candidates','url'=>route('candidates.index')],['label'=>$candidate->user->name]]"/><div class="mt-6 flex flex-wrap items-center gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="h-24 w-24 shrink-0 overflow-hidden rounded-full bg-slate-100">@if($candidate->profile_photo_path)<img src="{{ route('candidates.photo',$candidate->slug) }}" alt="{{ $candidate->user->name }}" class="h-full w-full object-cover">@else<span class="grid h-full place-items-center text-3xl font-bold text-slate-500">{{ mb_substr($candidate->user->name,0,1) }}</span>@endif</div><div class="min-w-0 flex-1"><p class="text-sm font-semibold uppercase tracking-wider text-brand-700">{{ str($candidate->availability_status)->replace('_',' ')->title() }}</p><h1 class="mt-1 text-3xl font-extrabold text-slate-950">{{ $candidate->user->name }}</h1><p class="mt-1 text-lg text-slate-700">{{ $candidate->headline }}</p><div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-500">@if($candidate->city || $candidate->state)<span>⌖ {{ collect([$candidate->city,$candidate->state])->filter()->join(', ') }}</span>@endif @if($candidate->experience_level)<span>{{ str($candidate->experience_level)->replace('_',' ')->title() }}</span>@endif @if($candidate->years_experience !== null)<span>{{ $candidate->years_experience }} years’ experience</span>@endif</div></div></div></div></section>
    <div class="mx-auto grid max-w-5xl gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[1fr_300px] lg:px-8">
        <div class="space-y-6">
            @if($candidate->about)<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">About</h2><p class="mt-3 whitespace-pre-line leading-7 text-slate-700">{{ $candidate->about }}</p></section>@endif
            @if($candidate->experiences->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Work experience</h2><div class="mt-4 space-y-5">@foreach($candidate->experiences as $experience)<article class="border-l-2 border-orange-200 pl-4"><h3 class="font-bold">{{ $experience->title }}</h3><p class="text-sm text-slate-700">{{ $experience->company }}@if($experience->location) · {{ $experience->location }}@endif</p><p class="mt-1 text-xs text-slate-500">{{ $experience->start_date?->format('M Y') }} – {{ $experience->is_current ? 'Present' : $experience->end_date?->format('M Y') }}</p>@if($experience->description)<p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $experience->description }}</p>@endif</article>@endforeach</div></section>@endif
            @if($candidate->educations->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Education</h2><div class="mt-4 space-y-4">@foreach($candidate->educations as $education)<article><h3 class="font-bold">{{ $education->qualification }}@if($education->field_of_study) · {{ $education->field_of_study }}@endif</h3><p class="text-sm text-slate-700">{{ $education->institution }}</p><p class="text-xs text-slate-500">{{ $education->start_date?->format('Y') }} – {{ $education->currently_studying ? 'Present' : $education->end_date?->format('Y') }}</p>@if($education->description)<p class="mt-2 whitespace-pre-line text-sm text-slate-600">{{ $education->description }}</p>@endif</article>@endforeach</div></section>@endif
            @if($candidate->portfolios->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Portfolio</h2><div class="mt-4 grid gap-4 sm:grid-cols-2">@foreach($candidate->portfolios as $item)<article class="rounded-xl bg-slate-50 p-4"><h3 class="font-bold">{{ $item->title }}</h3>@if($item->completed_at)<p class="text-xs text-slate-500">{{ $item->completed_at->format('M Y') }}</p>@endif@if($item->description)<p class="mt-2 whitespace-pre-line text-sm text-slate-600">{{ $item->description }}</p>@endif@if($item->url)<a href="{{ $item->url }}" target="_blank" rel="noopener noreferrer" class="mt-3 inline-block text-sm font-semibold text-brand-700">View project ↗</a>@endif</article>@endforeach</div></section>@endif
            @if($candidate->awards->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Awards & certifications</h2><div class="mt-4 space-y-4">@foreach($candidate->awards as $award)<article><h3 class="font-bold">{{ $award->title }}</h3><p class="text-sm text-slate-600">{{ $award->issuer }}@if($award->awarded_at) · {{ $award->awarded_at->format('M Y') }}@endif</p>@if($award->description)<p class="mt-2 text-sm text-slate-600">{{ $award->description }}</p>@endif</article>@endforeach</div></section>@endif
            @if($candidate->intro_video_url)<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">{{ $candidate->intro_video_title ?: 'Introduction video' }}</h2><a href="{{ $candidate->intro_video_url }}" target="_blank" rel="noopener noreferrer" class="mt-3 inline-flex rounded-lg border border-slate-300 px-4 py-2 font-semibold text-brand-700">Watch on {{ ucfirst($candidate->video_provider) }} ↗</a></section>@endif
        </div>
        <aside class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">Profile overview</h2>@if($candidate->show_expected_salary && $candidate->expected_salary)<p class="mt-3 text-sm text-slate-600">Expected salary</p><p class="font-semibold">{{ number_format($candidate->expected_salary) }} / {{ $candidate->salary_type ?: 'period not specified' }}</p>@endif@if($candidate->preferred_employment_types)<p class="mt-4 text-sm text-slate-600">Preferred work</p><p class="font-semibold">{{ collect($candidate->preferred_employment_types)->map(fn($type)=>str($type)->replace('_',' ')->title())->join(', ') }}</p>@endif@if($candidate->categories->isNotEmpty())<p class="mt-4 text-sm text-slate-600">Categories</p><div class="mt-2 flex flex-wrap gap-2">@foreach($candidate->categories as $category)<span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-900">{{ $category->name }}</span>@endforeach</div>@endif</section>
        @if($candidate->skills->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">Skills</h2><div class="mt-3 flex flex-wrap gap-2">@foreach($candidate->skills as $skill)<span class="rounded-full bg-orange-50 px-3 py-1 text-sm text-orange-900">{{ $skill->name }}</span>@endforeach</div></section>@endif
        @if($candidate->languages->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">Languages</h2><ul class="mt-3 space-y-2">@foreach($candidate->languages as $language)<li class="flex justify-between gap-2 text-sm"><span>{{ $language->language }}</span><span class="text-slate-500">{{ ucfirst($language->proficiency) }}</span></li>@endforeach</ul></section>@endif
        <section class="rounded-2xl bg-slate-900 p-6 text-white"><h2 class="font-bold">Professional links</h2><div class="mt-3 flex flex-col gap-2 text-sm">@foreach(['linkedin_url'=>'LinkedIn','website_url'=>'Website','portfolio_url'=>'Portfolio','facebook_url'=>'Facebook','twitter_url'=>'X / Twitter'] as $field=>$label)@if($candidate->$field)<a href="{{ $candidate->$field }}" target="_blank" rel="noopener noreferrer" class="text-blue-200 hover:underline">{{ $label }} ↗</a>@endif @endforeach</div></section></aside>
    </div>
@endsection
