<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><h1 class="text-xl font-bold text-slate-900">My candidate profile</h1>@if ($profile->is_public)<a class="font-semibold text-brand-700 hover:underline" href="{{ route('candidates.show', $profile->slug) }}">View public profile ↗</a>@endif</div></x-slot>

    <div class="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6">
        @if (session('status')) <div role="status" class="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('status') }}</div> @endif
        @if ($errors->any()) <div role="alert" class="rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-800">Please review the highlighted fields. {{ $errors->first() }}</div> @endif
        <nav aria-label="Profile sections" class="flex gap-2 overflow-x-auto rounded-xl bg-white p-3 shadow-sm">@foreach (['profile'=>'Profile','resume'=>'Resume','education'=>'Education','experience'=>'Experience','skills'=>'Skills','languages'=>'Languages','portfolio'=>'Portfolio','awards'=>'Awards'] as $id=>$label)<a class="shrink-0 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 hover:text-brand-700" href="#{{ $id }}">{{ $label }}</a>@endforeach</nav>

        <section id="profile" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm sm:p-8">
            <div class="flex flex-wrap items-center gap-5">
                <div class="h-24 w-24 overflow-hidden rounded-full bg-slate-100">@if($profile->profile_photo_path)<img src="{{ route('candidate.profile.photo') }}" alt="Your profile photo" class="h-full w-full object-cover">@else<div class="grid h-full place-items-center text-3xl text-slate-400">{{ mb_substr(auth()->user()->name,0,1) }}</div>@endif</div>
                <div class="min-w-0 flex-1"><h2 class="text-lg font-bold">Profile photo</h2><p class="mt-1 text-sm text-slate-600">JPG, PNG or WebP up to 2 MB. Kept private unless your profile is public.</p><form method="POST" enctype="multipart/form-data" action="{{ route('candidate.profile.photo.store') }}" class="mt-3 flex flex-wrap gap-2">@csrf<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required class="max-w-full text-sm"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Upload photo</button></form>@if($profile->profile_photo_path)<form method="POST" action="{{ route('candidate.profile.photo.destroy') }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove photo</button></form>@endif</div>
            </div>
            <form method="POST" action="{{ route('candidate.profile.update') }}" class="mt-8 space-y-6">@csrf @method('PATCH')
                <div><h2 class="text-lg font-bold">Professional details</h2><p class="text-sm text-slate-600">Only the fields marked public are visible to employers and directory visitors.</p></div>
                <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    @foreach (['name'=>'Full name','headline'=>'Professional headline','phone'=>'Phone (private)','city'=>'City','state'=>'State','country'=>'Country','years_experience'=>'Years of experience','months_experience'=>'Additional months','expected_salary'=>'Expected salary','address'=>'Address (private)','linkedin_url'=>'LinkedIn URL','facebook_url'=>'Facebook URL','twitter_url'=>'X / Twitter URL','website_url'=>'Website URL','portfolio_url'=>'Portfolio URL'] as $field=>$label)
                        <label class="block text-sm font-medium text-slate-700">{{ $label }}<input name="{{ $field }}" value="{{ old($field, $field === 'name' ? auth()->user()->name : $profile->$field) }}" class="mt-1 w-full rounded-lg border-slate-300" @if(in_array($field,['years_experience','months_experience','expected_salary'])) type="number" min="0" @endif></label>
                    @endforeach
                    <label class="block text-sm font-medium text-slate-700">Date of birth (private)<input type="date" name="date_of_birth" value="{{ old('date_of_birth', $profile->date_of_birth?->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
                    <label class="block text-sm font-medium text-slate-700">Gender (private)<select name="gender" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Prefer not to say</option>@foreach(['woman'=>'Woman','man'=>'Man','non_binary'=>'Non-binary','self_described'=>'Self-described','prefer_not_to_say'=>'Prefer not to say'] as $v=>$l)<option value="{{ $v }}" @selected(old('gender',$profile->gender)===$v)>{{ $l }}</option>@endforeach</select></label>
                    <label class="block text-sm font-medium text-slate-700">Experience level<select name="experience_level" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Choose</option>@foreach(['entry'=>'Entry level','junior'=>'Junior','mid'=>'Mid-level','senior'=>'Senior','lead'=>'Lead','executive'=>'Executive'] as $v=>$l)<option value="{{ $v }}" @selected(old('experience_level',$profile->experience_level)===$v)>{{ $l }}</option>@endforeach</select></label>
                    <label class="block text-sm font-medium text-slate-700">Salary period<select name="salary_type" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Choose</option>@foreach(['yearly'=>'Yearly','monthly'=>'Monthly','hourly'=>'Hourly'] as $v=>$l)<option value="{{ $v }}" @selected(old('salary_type',$profile->salary_type)===$v)>{{ $l }}</option>@endforeach</select></label>
                    <label class="block text-sm font-medium text-slate-700">Availability<select name="availability_status" class="mt-1 w-full rounded-lg border-slate-300">@foreach(['open_to_work'=>'Open to work','passively_looking'=>'Open to opportunities','not_looking'=>'Not looking'] as $v=>$l)<option value="{{ $v }}" @selected(old('availability_status',$profile->availability_status)===$v)>{{ $l }}</option>@endforeach</select></label>
                </div>
                <label class="block text-sm font-medium text-slate-700">About me<textarea name="about" rows="5" maxlength="3000" class="mt-1 w-full rounded-lg border-slate-300">{{ old('about',$profile->about) }}</textarea></label>
                <div><h3 class="font-semibold">Preferred employment types</h3><div class="mt-2 flex flex-wrap gap-4">@foreach(['full_time'=>'Full-time','part_time'=>'Part-time','contract'=>'Contract','temporary'=>'Temporary','internship'=>'Internship'] as $v=>$l)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="preferred_employment_types[]" value="{{ $v }}" @checked(in_array($v,old('preferred_employment_types',$profile->preferred_employment_types ?? [])))>{{ $l }}</label>@endforeach</div></div>
                <div><h3 class="font-semibold">Professional categories</h3><input type="hidden" name="categories_present" value="1"><div class="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($categories as $category)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="categories[]" value="{{ $category->id }}" @checked(in_array($category->id,old('categories',$profile->categories->modelKeys())))>{{ $category->name }}</label>@endforeach</div></div>
                <div class="grid gap-3 sm:grid-cols-2"><label class="flex items-center gap-2 text-sm"><input type="hidden" name="show_expected_salary" value="0"><input type="checkbox" name="show_expected_salary" value="1" @checked(old('show_expected_salary',$profile->show_expected_salary))>Show expected salary on my public profile</label><label class="flex items-center gap-2 text-sm"><input type="hidden" name="is_public" value="0"><input type="checkbox" name="is_public" value="1" @checked(old('is_public',$profile->is_public))>Make my profile visible in the public candidate directory</label></div>
                <div class="border-t pt-5"><h3 class="font-semibold">Introduction video</h3><p class="text-sm text-slate-600">Use a secure YouTube or Vimeo link. The provider and link must match.</p><div class="mt-3 grid gap-4 sm:grid-cols-3"><label class="text-sm">Provider<select name="video_provider" class="mt-1 w-full rounded-lg border-slate-300"><option value="">None</option>@foreach(['youtube'=>'YouTube','vimeo'=>'Vimeo'] as $v=>$l)<option value="{{ $v }}" @selected(old('video_provider',$profile->video_provider)===$v)>{{ $l }}</option>@endforeach</select></label><label class="text-sm sm:col-span-2">Video URL<input name="intro_video_url" value="{{ old('intro_video_url',$profile->intro_video_url) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm sm:col-span-3">Video title<input name="intro_video_title" value="{{ old('intro_video_title',$profile->intro_video_title) }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div></div>
                <button class="rounded-lg bg-brand-700 px-5 py-3 text-sm font-bold text-white">Save profile</button>
            </form>
        </section>

        <section id="resume" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Resume</h2><p class="mt-1 text-sm text-slate-600">Private by default. Only you can download it from your account.</p>@if($profile->resume_path)<div class="mt-4 flex flex-wrap items-center gap-3 rounded-lg bg-slate-50 p-4"><span class="flex-1">{{ $profile->resume_title ?: $profile->resume_original_name }} <span class="text-sm text-slate-500">{{ $profile->resume_size ? number_format($profile->resume_size / 1024).' KB' : '' }}</span></span><a class="font-semibold text-brand-700" href="{{ route('candidate.resume.download') }}">Download</a><form method="POST" action="{{ route('candidate.resume.destroy') }}">@csrf @method('DELETE')<button class="font-semibold text-rose-700">Remove</button></form></div>@endif<form method="POST" enctype="multipart/form-data" action="{{ route('candidate.resume.store') }}" class="mt-4 flex flex-wrap items-end gap-3">@csrf<label class="text-sm">Resume title (optional)<input name="resume_title" class="mt-1 block rounded-lg border-slate-300"></label><label class="text-sm">PDF, DOC or DOCX (max 5 MB)<input type="file" name="resume" accept=".pdf,.doc,.docx" required class="mt-1 block max-w-full"></label><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Upload / replace</button></form></section>

        <section id="education" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Education</h2>@foreach($profile->educations as $education)<div class="my-4 rounded-lg border p-4"><form method="POST" action="{{ route('candidate.educations.update',$education) }}" class="grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input required name="institution" value="{{ $education->institution }}" placeholder="Institution" class="rounded-lg border-slate-300"><input required name="qualification" value="{{ $education->qualification }}" placeholder="Qualification" class="rounded-lg border-slate-300"><input name="field_of_study" value="{{ $education->field_of_study }}" placeholder="Field of study" class="rounded-lg border-slate-300"><input type="date" name="start_date" value="{{ $education->start_date?->format('Y-m-d') }}" class="rounded-lg border-slate-300"><input type="date" name="end_date" value="{{ $education->end_date?->format('Y-m-d') }}" class="rounded-lg border-slate-300"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="currently_studying" value="1" @checked($education->currently_studying)>Currently studying</label><textarea name="description" placeholder="Details" class="rounded-lg border-slate-300 sm:col-span-2">{{ $education->description }}</textarea><button class="justify-self-start font-semibold text-brand-700">Save changes</button></form><form method="POST" action="{{ route('candidate.educations.destroy',$education) }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove education</button></form></div>@endforeach<form method="POST" action="{{ route('candidate.educations.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input required name="institution" placeholder="Institution" class="rounded-lg border-slate-300"><input required name="qualification" placeholder="Qualification" class="rounded-lg border-slate-300"><input name="field_of_study" placeholder="Field of study" class="rounded-lg border-slate-300"><input type="date" name="start_date" class="rounded-lg border-slate-300"><input type="date" name="end_date" class="rounded-lg border-slate-300"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="currently_studying" value="1">Currently studying</label><textarea name="description" placeholder="Details" class="rounded-lg border-slate-300 sm:col-span-2"></textarea><button class="justify-self-start rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add education</button></form></section>

        <section id="experience" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Work experience</h2>@foreach($profile->experiences as $experience)<div class="my-4 rounded-lg border p-4"><form method="POST" action="{{ route('candidate.experiences.update',$experience) }}" class="grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input required name="title" value="{{ $experience->title }}" placeholder="Job title" class="rounded-lg border-slate-300"><input required name="company" value="{{ $experience->company }}" placeholder="Company" class="rounded-lg border-slate-300"><input name="location" value="{{ $experience->location }}" placeholder="Location" class="rounded-lg border-slate-300"><input required type="date" name="start_date" value="{{ $experience->start_date?->format('Y-m-d') }}" class="rounded-lg border-slate-300"><input type="date" name="end_date" value="{{ $experience->end_date?->format('Y-m-d') }}" class="rounded-lg border-slate-300"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_current" value="1" @checked($experience->is_current)>Current role</label><textarea name="description" placeholder="What you did" class="rounded-lg border-slate-300 sm:col-span-2">{{ $experience->description }}</textarea><button class="justify-self-start font-semibold text-brand-700">Save changes</button></form><form method="POST" action="{{ route('candidate.experiences.destroy',$experience) }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove experience</button></form></div>@endforeach<form method="POST" action="{{ route('candidate.experiences.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input required name="title" placeholder="Job title" class="rounded-lg border-slate-300"><input required name="company" placeholder="Company" class="rounded-lg border-slate-300"><input name="location" placeholder="Location" class="rounded-lg border-slate-300"><input required type="date" name="start_date" class="rounded-lg border-slate-300"><input type="date" name="end_date" class="rounded-lg border-slate-300"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_current" value="1">Current role</label><textarea name="description" placeholder="What you did" class="rounded-lg border-slate-300 sm:col-span-2"></textarea><button class="justify-self-start rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add experience</button></form></section>

        <section id="skills" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Skills</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($profile->skills as $skill)<span class="inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-2 text-sm text-orange-900">{{ $skill->name }} · {{ ucfirst($skill->pivot->proficiency) }}<form method="POST" action="{{ route('candidate.skills.destroy',$skill) }}">@csrf @method('DELETE')<button aria-label="Remove {{ $skill->name }}" class="font-bold">×</button></form></span>@endforeach</div><form method="POST" action="{{ route('candidate.skills.store') }}" class="mt-4 flex flex-wrap gap-3">@csrf<input name="name" list="skill-options" placeholder="Add a skill" required class="min-w-48 rounded-lg border-slate-300"><datalist id="skill-options">@foreach($availableSkills as $skill)<option value="{{ $skill->name }}">@endforeach</datalist><select name="proficiency" class="rounded-lg border-slate-300">@foreach(['beginner','intermediate','advanced','expert'] as $level)<option value="{{ $level }}">{{ ucfirst($level) }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add skill</button></form></section>

        <section id="languages" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Languages</h2>@foreach($profile->languages as $language)<div class="my-3 flex flex-wrap items-center gap-3"><form method="POST" action="{{ route('candidate.languages.update',$language) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<input name="language" value="{{ $language->language }}" required class="rounded-lg border-slate-300"><select name="proficiency" class="rounded-lg border-slate-300">@foreach(['basic','intermediate','fluent','native'] as $level)<option value="{{ $level }}" @selected($language->proficiency===$level)>{{ ucfirst($level) }}</option>@endforeach</select><button class="font-semibold text-brand-700">Save</button></form><form method="POST" action="{{ route('candidate.languages.destroy',$language) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove</button></form></div>@endforeach<form method="POST" action="{{ route('candidate.languages.store') }}" class="mt-4 flex flex-wrap gap-2">@csrf<input required name="language" placeholder="Language" class="rounded-lg border-slate-300"><select name="proficiency" class="rounded-lg border-slate-300">@foreach(['basic','intermediate','fluent','native'] as $level)<option value="{{ $level }}">{{ ucfirst($level) }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add language</button></form></section>

        <section id="portfolio" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Portfolio</h2>@foreach($profile->portfolios as $item)<div class="my-3 rounded-lg border p-4"><form method="POST" action="{{ route('candidate.portfolios.update',$item) }}" class="grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input required name="title" value="{{ $item->title }}" class="rounded-lg border-slate-300"><input name="url" value="{{ $item->url }}" placeholder="Project URL" class="rounded-lg border-slate-300"><input type="date" name="completed_at" value="{{ $item->completed_at?->format('Y-m-d') }}" class="rounded-lg border-slate-300"><textarea name="description" class="rounded-lg border-slate-300 sm:col-span-2">{{ $item->description }}</textarea><button class="justify-self-start font-semibold text-brand-700">Save</button></form><form method="POST" action="{{ route('candidate.portfolios.destroy',$item) }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove</button></form></div>@endforeach<form method="POST" action="{{ route('candidate.portfolios.store') }}" class="mt-4 grid gap-2 sm:grid-cols-2">@csrf<input required name="title" placeholder="Project title" class="rounded-lg border-slate-300"><input name="url" placeholder="Project URL" class="rounded-lg border-slate-300"><input type="date" name="completed_at" class="rounded-lg border-slate-300"><textarea name="description" placeholder="Description" class="rounded-lg border-slate-300 sm:col-span-2"></textarea><button class="justify-self-start rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add portfolio item</button></form></section>

        <section id="awards" class="scroll-mt-24 rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Awards & certifications</h2>@foreach($profile->awards as $award)<div class="my-3 rounded-lg border p-4"><form method="POST" action="{{ route('candidate.awards.update',$award) }}" class="grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input required name="title" value="{{ $award->title }}" class="rounded-lg border-slate-300"><input name="issuer" value="{{ $award->issuer }}" placeholder="Issuer" class="rounded-lg border-slate-300"><input type="date" name="awarded_at" value="{{ $award->awarded_at?->format('Y-m-d') }}" class="rounded-lg border-slate-300"><textarea name="description" class="rounded-lg border-slate-300 sm:col-span-2">{{ $award->description }}</textarea><button class="justify-self-start font-semibold text-brand-700">Save</button></form><form method="POST" action="{{ route('candidate.awards.destroy',$award) }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove</button></form></div>@endforeach<form method="POST" action="{{ route('candidate.awards.store') }}" class="mt-4 grid gap-2 sm:grid-cols-2">@csrf<input required name="title" placeholder="Award or certification" class="rounded-lg border-slate-300"><input name="issuer" placeholder="Issuer" class="rounded-lg border-slate-300"><input type="date" name="awarded_at" class="rounded-lg border-slate-300"><textarea name="description" placeholder="Description" class="rounded-lg border-slate-300 sm:col-span-2"></textarea><button class="justify-self-start rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add award</button></form></section>
    </div>
</x-app-layout>
