<?php

use App\Http\Controllers\CandidateProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
*/

Route::get('/', HomeController::class)->name('home');
Route::view('/jobs', 'jobs.index')->name('jobs.index');
Route::get('/candidates', [PublicPageController::class, 'candidates'])->name('candidates.index');
Route::get('/companies', [PublicPageController::class, 'companies'])->name('companies.index');
Route::get('/companies/{company:slug}', [PublicPageController::class, 'showCompany'])->name('companies.show');
Route::get('/blog', [PublicPageController::class, 'blog'])->name('blog.index');
Route::get('/about', [PublicPageController::class, 'about'])->name('about');
Route::get('/contact', [PublicPageController::class, 'contact'])->name('contact');

/*
|--------------------------------------------------------------------------
| Auth Routes (login, register, password reset, etc.)
| Generated by Laravel Breeze scaffold.
|--------------------------------------------------------------------------
*/

require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Authenticated Routes (any logged-in user)
|--------------------------------------------------------------------------
*/

Route::middleware('auth')->group(function () {

    // Generic dashboard — redirects to the correct role-specific dashboard.
    Route::get('/dashboard', function () {
        $user = auth()->user();

        return match (true) {
            $user->isCandidate() => redirect()->route('candidate.dashboard'),
            $user->isEmployer() => redirect()->route('employer.dashboard'),
            $user->isAdmin() => redirect()->route('admin.dashboard'),
            $user->isOwner() => redirect()->route('admin.dashboard'),
            default => redirect()->route('home'),
        };
    })->name('dashboard');

    // Profile (any authenticated user)
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

/*
|--------------------------------------------------------------------------
| Candidate Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:candidate'])->prefix('candidate')->name('candidate.')->group(function () {
    Route::view('/dashboard', 'candidate.dashboard')->name('dashboard');
    Route::get('/profile', [CandidateProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [CandidateProfileController::class, 'update'])->name('profile.update');
    Route::post('/resume', [CandidateProfileController::class, 'uploadResume'])->name('resume.store');
    Route::post('/skills', [CandidateProfileController::class, 'addSkill'])->name('skills.store');
    Route::delete('/skills/{skill}', [CandidateProfileController::class, 'removeSkill'])->name('skills.destroy');
});

/*
|--------------------------------------------------------------------------
| Employer Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:employer'])->prefix('employer')->name('employer.')->group(function () {
    Route::view('/dashboard', 'employer.dashboard')->name('dashboard');
});

/*
|--------------------------------------------------------------------------
| Admin / Owner Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:admin,owner'])->prefix('admin')->name('admin.')->group(function () {
    Route::view('/dashboard', 'admin.dashboard')->name('dashboard');
});
