<?php

use App\Http\Controllers\CandidateDashboardController;
use App\Http\Controllers\CandidateDirectoryController;
use App\Http\Controllers\CandidateProfileController;
use App\Http\Controllers\CandidateProfileResourceController;
use App\Http\Controllers\CandidateSavedJobsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobApplicationController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
*/

Route::get('/', HomeController::class)->name('home');
Route::view('/jobs', 'jobs.index')->name('jobs.index');
Route::get('/jobs/{job:slug}', [JobController::class, 'show'])->name('jobs.show');
Route::get('/jobs/{job:slug}/apply', [JobApplicationController::class, 'create'])->middleware(['auth', 'role:candidate'])->name('jobs.apply');
Route::post('/jobs/{job:slug}/apply', [JobApplicationController::class, 'store'])->middleware(['auth', 'role:candidate'])->name('jobs.apply.store');
Route::get('/candidates', [CandidateDirectoryController::class, 'index'])->name('candidates.index');
Route::get('/candidates/{candidate:slug}/photo', [CandidateDirectoryController::class, 'photo'])->name('candidates.photo');
Route::get('/candidates/{candidate:slug}', [CandidateDirectoryController::class, 'show'])->name('candidates.show');
Route::get('/companies', [PublicPageController::class, 'companies'])->name('companies.index');
Route::get('/companies/{company:slug}', [PublicPageController::class, 'showCompany'])->name('companies.show');
Route::get('/blog', [PublicPageController::class, 'blog'])->name('blog.index');
Route::get('/about', [PublicPageController::class, 'about'])->name('about');
Route::get('/contact', [PublicPageController::class, 'contact'])->name('contact');

/*
|--------------------------------------------------------------------------
| Auth Routes (login, register, password reset, etc.)
| Generated by Laravel Breeze scaffold.
|--------------------------------------------------------------------------
*/

require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Authenticated Routes (any logged-in user)
|--------------------------------------------------------------------------
*/

Route::middleware('auth')->group(function () {

    // Generic dashboard — redirects to the correct role-specific dashboard.
    Route::get('/dashboard', function () {
        $user = auth()->user();

        return match (true) {
            $user->isCandidate() => redirect()->route('candidate.dashboard'),
            $user->isEmployer() => redirect()->route('employer.dashboard'),
            $user->isAdmin() => redirect()->route('admin.dashboard'),
            $user->isOwner() => redirect()->route('admin.dashboard'),
            default => redirect()->route('home'),
        };
    })->name('dashboard');

    // Profile (any authenticated user)
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

/*
|--------------------------------------------------------------------------
| Candidate Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:candidate'])->prefix('candidate')->name('candidate.')->group(function () {
    Route::get('/dashboard', CandidateDashboardController::class)->name('dashboard');
    Route::get('/saved-jobs', [CandidateSavedJobsController::class, 'index'])->name('saved-jobs.index');
    Route::delete('/saved-jobs/{savedJob}', [CandidateSavedJobsController::class, 'destroy'])->name('saved-jobs.destroy');
    Route::post('/jobs/{job:slug}/save', [CandidateSavedJobsController::class, 'store'])->name('jobs.save');
    Route::get('/profile', [CandidateProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [CandidateProfileController::class, 'update'])->name('profile.update');
    Route::get('/profile/photo', [CandidateProfileController::class, 'photo'])->name('profile.photo');
    Route::post('/profile/photo', [CandidateProfileController::class, 'uploadPhoto'])->name('profile.photo.store');
    Route::delete('/profile/photo', [CandidateProfileController::class, 'deletePhoto'])->name('profile.photo.destroy');
    Route::post('/resume', [CandidateProfileController::class, 'uploadResume'])->name('resume.store');
    Route::get('/resume', [CandidateProfileController::class, 'downloadResume'])->name('resume.download');
    Route::delete('/resume', [CandidateProfileController::class, 'deleteResume'])->name('resume.destroy');
    Route::post('/skills', [CandidateProfileController::class, 'addSkill'])->name('skills.store');
    Route::delete('/skills/{skill}', [CandidateProfileController::class, 'removeSkill'])->name('skills.destroy');
    Route::post('/education', [CandidateProfileResourceController::class, 'storeEducation'])->name('educations.store');
    Route::put('/education/{education}', [CandidateProfileResourceController::class, 'updateEducation'])->name('educations.update');
    Route::delete('/education/{education}', [CandidateProfileResourceController::class, 'destroyEducation'])->name('educations.destroy');
    Route::post('/experience', [CandidateProfileResourceController::class, 'storeExperience'])->name('experiences.store');
    Route::put('/experience/{experience}', [CandidateProfileResourceController::class, 'updateExperience'])->name('experiences.update');
    Route::delete('/experience/{experience}', [CandidateProfileResourceController::class, 'destroyExperience'])->name('experiences.destroy');
    Route::post('/languages', [CandidateProfileResourceController::class, 'storeLanguage'])->name('languages.store');
    Route::put('/languages/{language}', [CandidateProfileResourceController::class, 'updateLanguage'])->name('languages.update');
    Route::delete('/languages/{language}', [CandidateProfileResourceController::class, 'destroyLanguage'])->name('languages.destroy');
    Route::post('/portfolio', [CandidateProfileResourceController::class, 'storePortfolio'])->name('portfolios.store');
    Route::put('/portfolio/{portfolio}', [CandidateProfileResourceController::class, 'updatePortfolio'])->name('portfolios.update');
    Route::delete('/portfolio/{portfolio}', [CandidateProfileResourceController::class, 'destroyPortfolio'])->name('portfolios.destroy');
    Route::post('/awards', [CandidateProfileResourceController::class, 'storeAward'])->name('awards.store');
    Route::put('/awards/{award}', [CandidateProfileResourceController::class, 'updateAward'])->name('awards.update');
    Route::delete('/awards/{award}', [CandidateProfileResourceController::class, 'destroyAward'])->name('awards.destroy');
});

/*
|--------------------------------------------------------------------------
| Employer Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:employer'])->prefix('employer')->name('employer.')->group(function () {
    Route::view('/dashboard', 'employer.dashboard')->name('dashboard');
});

/*
|--------------------------------------------------------------------------
| Admin / Owner Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:admin,owner'])->prefix('admin')->name('admin.')->group(function () {
    Route::view('/dashboard', 'admin.dashboard')->name('dashboard');
});
