<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
*/

Route::view('/', 'welcome')->name('home');

/*
|--------------------------------------------------------------------------
| Auth Routes (login, register, password reset, etc.)
| Generated by Laravel Breeze scaffold.
|--------------------------------------------------------------------------
*/

require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Authenticated Routes (any logged-in user)
|--------------------------------------------------------------------------
*/

Route::middleware('auth')->group(function () {

    // Generic dashboard — redirects to the correct role-specific dashboard.
    Route::get('/dashboard', function () {
        $user = auth()->user();

        return match (true) {
            $user->isCandidate() => redirect()->route('candidate.dashboard'),
            $user->isEmployer() => redirect()->route('employer.dashboard'),
            $user->isAdmin() => redirect()->route('admin.dashboard'),
            $user->isOwner() => redirect()->route('admin.dashboard'),
            default => redirect()->route('home'),
        };
    })->name('dashboard');

    // Profile (any authenticated user)
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

/*
|--------------------------------------------------------------------------
| Candidate Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:candidate'])->prefix('candidate')->name('candidate.')->group(function () {
    Route::view('/dashboard', 'candidate.dashboard')->name('dashboard');
});

/*
|--------------------------------------------------------------------------
| Employer Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:employer'])->prefix('employer')->name('employer.')->group(function () {
    Route::view('/dashboard', 'employer.dashboard')->name('dashboard');
});

/*
|--------------------------------------------------------------------------
| Admin / Owner Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['auth', 'role:admin,owner'])->prefix('admin')->name('admin.')->group(function () {
    Route::view('/dashboard', 'admin.dashboard')->name('dashboard');
});
